### ISSUE TITLE
The Yino Widget and Speedtest Widget occasionally experience API errors.

### ISSUE THREAD

**Issue by minemine-m** [NigulasiZhao/homepage#1]
"version": "0.9.6"

**Comment by minemine-m** [comment]
Hey, buddy, this component is extremely important to me. Can you prioritize it?

**Comment by NigulasiZhao** [comment]
> 嘿，伙计，这个组件对我来说非常重要。您能确定优先级吗？

Hey bro, Please update your **cnspeedtest** to the latest version to resolve this issue

**Comment by minemine-m** [comment]
good job
